name: "build"

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  builds:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            image: null
            display: ubuntu
            deps: "echo no deps"
          - name: ubuntu-latest
            image: alpine:latest
            display: alpine
            deps: apk add make tar
          - name: macos-latest
            image: null
            display: macos
            deps: "echo no deps"
    runs-on: ${{ matrix.os.name }}
    name: ${{ matrix.os.display }}
    container:
      image: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - name: "deps"
        run: ${{ matrix.os.deps }}
      - name: "build"
        run: make VERSION=${GITHUB_SHA} check
